apiVersion: apps/v1
kind: Deployment
metadata:
  name: coco-helloworld-py
  labels:
    apps.coco-serverless/name: helloworld-py
  annotations: 
    io.containerd.cri.runtime-handler: kata-qemu-sev
spec:
  replicas: 1
  selector:
    matchLabels:
      apps.coco-serverless/name: helloworld-py
  template:
    metadata:
      labels:
        apps.coco-serverless/name: helloworld-py
        io.katacontainers.config.pre_attestation.enabled: "false" 
    spec:
      runtimeClassName: kata-qemu-sev
      containers:
      - name: helloworld-py
        image: registry.coco-csg.com/hello-world-flask:unencrypted
        ports:
        - containerPort: 8080

